services:
  - type: web
    name: bhouma
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bhouma-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: BASE_URL
        sync: false
      - key: META_APP_ID
        sync: false
      - key: META_APP_SECRET
        sync: false
      - key: LINKEDIN_CLIENT_ID
        sync: false
      - key: LINKEDIN_CLIENT_SECRET
        sync: false

databases:
  - name: bhouma-db
    plan: free
